### PR TITLE
Update Add-Table.ps1

### PR DESCRIPTION
**Pull request by yannovski**
Added Autofit parameter to allow resizing of columns on the target worksheet to automatically fit the data in the new table.

### CODE REVIEW

**Comment by RamblingCookieMonster** [comment]
Cool idea!  Have you run this locally to validate it works?  If so, happy to merge now : )

**Comment by yannovski** [comment]
Yep, worked well for me :)

Thanks for the module, works really well!

**Comment by RamblingCookieMonster** [comment]
Alrighty, lets see if the build process still works - thanks for submitting this!

**Comment by RamblingCookieMonster** [comment]
Oh!  Damn, I don't deploy automatically with this repo - will push up to the gallery at some point might be a day or two

**Pull request merged**
