### PR TITLE
Add basic table support

### PR DESCRIPTION
**Pull request by awiddersheim**
Added basic table support and fixed some small code style things along
the way.

### CODE REVIEW

**Comment by awiddersheim** [comment]
I should probably be writing tests for these....

**Comment by RamblingCookieMonster** [comment]
Haha, I tell myself that every time I add a bunch of parameters or function.  AppVeyor automatically runs the [PSExcel.Tests.ps1](https://github.com/RamblingCookieMonster/PSExcel/blob/master/Tests/PSExcel.Tests.ps1) against PowerShell 2 and native (4 IIRC) if you want to add them.  I've been adding superficial tests that show it didn't catastrophically fail : )

Question on this one, and I could go either way - does it make sense to have the Table switch and the default TableStyle, rather than handling similar to ChartType (treat the specification of ChartType as an implicit 'switch')?

I suppose tables are less diverse than charts, so it might make sense to keep it this way, unlike ChartType (would be harder to pick a default chart type)?

Your call, I'm happy either way - thanks for contributing!

**Comment by awiddersheim** [comment]
Your welcome. This solved an itch of mine. Excel, COM's and scheduled tasks all mixed up is not a fun problem to solve. Rather contribute to this, solving things the right way and never have to deal with it ever again.

So, just so I'm clear on what your asking, your saying that when `$TableType` is specified that should implicitly set table creation as well? So you'd kind of change the code like this

```
elseif($Table -or $TableType)
{
   # create table
}
```

Or you'd get rid of the `-Table` parameter and just have `-TableType` and use only that to specify a table should get created.

**Comment by RamblingCookieMonster** [comment]
Yep, similar motivation here, COM is fun : )

I meant the latter, but think your original implementation makes more sense for tables (for charts, it's harder to say 'oh, pie chart is what everyone will generally use').  Merging

Cheers!

**Comment by awiddersheim** [comment]
Awesome. Thanks!

**Pull request merged**
